NODE_DISCOVERY_STATUS_MAP = {
    0: "unknown",
    1: "in_progress",
    2: "finished",
    3: "error",
    4: "not_scheduled",
    5: "scheduled",
    6: "not_completed",
    7: "canceling",
    8: "ready_for_import",
}

NODE_STATUS_MAP = {
    0: "Unknown",
    1: "Up",
    2: "Down",
    3: "Warning",
    4: "Shutdown",
    5: "Testing",
    6: "Dormant",
    7: "NotPresent",
    8: "LowerLayerDown",
    9: "Unmanaged",
    10: "Unplugged",
    11: "External",
    12: "Unreachable",
    14: "Critical",
    15: "PartlyAvailable",
    16: "Misconfigured",
    17: "Undefined",
    19: "Unconfirmed",
    22: "Active",
    24: "Inactive",
    25: "Expired",
    26: "MonitoringDisabled",
    27: "Disabled",
    28: "NotLicensed",
    29: "OtherCategory",
    30: "NotRunning",
    31: "Online",
    32: "OnBattery",
    33: "OnSmartBoost",
    34: "TimedSleeping",
    35: "SoftwareBypass",
    36: "Off",
    37: "Rebooting",
    38: "SwitchedBypass",
    39: "HardwareFailureBypass",
    40: "SleepingUntilPowerReturn",
    41: "OnSmartTrim",
    42: "EcoMode",
    43: "HotStandBy",
    44: "OnBatteryTest",
}
